apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - my-telecom-portal-deployment.yaml
  - my-telecom-portal-service.yaml
  - my-telecom-account-deployment.yaml
  - my-telecom-account-service.yaml
  - my-portal-ui-deployment.yaml
  - my-portal-ui-service.yaml
