apiVersion: v1
kind: Service
metadata:
  name: my-portal-ui
  labels:
    app.kubernetes.io/name: my-portal-ui
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: telecom-network
spec:
  type: LoadBalancer
  ports:
    - port: 4200
      targetPort: 4200
      protocol: TCP
  loadBalancerSourceRanges:
    - 0.0.0.0/0
  selector:
    app.kubernetes.io/name: my-portal-ui
