apiVersion: v1
kind: Service
metadata:
 name: my-portal-ui
 labels:
   name: my-portal-ui
spec:
 type: LoadBalancer
 ports:
   - port: 4200
     targetPort: 4200
     protocol: TCP
 loadBalancerSourceRanges: 
   - 0.0.0.0/0
 selector:
   run: my-portal-ui

