apiVersion: v1
kind: Service
metadata:
 name: my-telecom-account
 labels:
   name: my-telecom-account
spec:
 type: LoadBalancer
 ports:
   - port: 8282
     targetPort: 8282
     protocol: TCP
 loadBalancerSourceRanges: 
   - 0.0.0.0/0
 selector:
   run: my-telecom-account

