apiVersion: v1
kind: Service
metadata:
 name: my-telecom-portal
 labels:
   name: my-telecom-portal
spec:
 type: LoadBalancer
 ports:
   - port: 8181
     targetPort: 8181
     protocol: TCP
 loadBalancerSourceRanges: 
   - 0.0.0.0/0
 selector:
   run: my-telecom-portal

