version: '3'

services:

  my-telecom-portal:
    image: arnabdey14/my-telecom-portal:v1 
    ports:
      - "443:8001"
    environment:
      - reschedule=on-node-failure
      - restart=always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 3

  my-telecom-account:
    image: arnabdey14/my-telecom-account:v1
    ports:
      - "8443:8002"
    environment:    
      - reschedule=on-node-failure
       - restart=always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - my-telecom-portal

  my-portal-ui:
    image: arnabdey14/my-portal-ui:v2
    ports:
      - "80:8080"
    environment:
      - reschedule=on-node-failure
      - restart=always
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - my-telecom-portal

networks:
    overlay:
