services:

  my-telecom-portal:
    build: ./services/my-telecom-portal
    image: ghcr.io/arnabdey73/my-telecom-portal:dev
    ports:
      - "8181:8181"
    restart: unless-stopped

  my-telecom-account:
    build: ./services/my-telecom-account
    image: ghcr.io/arnabdey73/my-telecom-account:dev
    ports:
      - "8282:8282"
    restart: unless-stopped
    depends_on:
      - my-telecom-portal

  my-portal-ui:
    build: ./services/my-portal-ui
    image: ghcr.io/arnabdey73/my-portal-ui:dev
    ports:
      - "4200:4200"
    restart: unless-stopped
    depends_on:
      - my-telecom-portal
